---
version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: hsa-8-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/cache:/data/nginx/cache
    ports:
      - "80:80"
    links:
      - app
  app:
    image: nginx:latest
    container_name: hsa-8-app
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/nginx.conf
      - ./images:/data/images
      - ./html:/data/www
    ports:
      - "8080:80"
